#spring.application.name=hm-notification
#server.port=8600
#
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=your_email@gmail.com
#spring.mail.password=your_app_password   # use App Password, not real Gmail password
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
#twilio.account.sid=your_twilio_account_sid
#twilio.auth.token=your_twilio_auth_token
#twilio.phone.number=your_twilio_phone_number
