server:
  port: 8765  # Gateway's port

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enables service discovery for routes
      routes:
        - id: service_a_route
          uri: Harish:servicea  # Load-balanced URI for Eureka service 'service-a'
          predicates:
            - Path=/servicea/**
        - id: swagger_service_a
          uri: Harish:servicea
          predicates:
            - Path=/servicea/v3/api-docs
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html  # Expose Swagger UI at this endpoint

