spring.application.name=hm-food-service
server.port=8001
server.servlet.context-path=/hotel/food

#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=false
#springdoc.swagger-ui.override-with-gateway-url=true
