<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.6.7</version>
		<relativePath />
	</parent>
	<groupId>com.hm.parent</groupId>
	<artifactId>hm-parent-service</artifactId>
	<version>1.0.0.0-SNAPSHOT</version>
	<name>hm-parent-service</name>
	<description>Parent Service</description>

	<packaging>pom</packaging>
	<properties>
		<java.version>1.8</java.version>
		<spring-cloud.version>2021.0.5</spring-cloud.version>
		<auth-service-version>1.0.0.0-SNAPSHOT</auth-service-version>
		<onboard-service-version>1.0.0.0-SNAPSHOT</onboard-service-version>
		<eureka-service-version>1.0.0.0-SNAPSHOT</eureka-service-version>
		<common-utils-version>1.0.0.0-SNAPSHOT</common-utils-version>
		<food-service-version>1.0.0.0-SNAPSHOT</food-service-version>
	</properties>
	<dependencies>

	</dependencies>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<!--<modules>
		<module>../hm-auth-service</module>
	</modules>-->

	<profiles>
		<profile>
			<id>build-common-util</id>
			<modules>
				<module>../hm-common-utils</module>
			</modules>
		</profile>
		<profile>
			<id>build-all</id>
			
			<modules>
				<module>../hm-auth-service</module>
				<module>../hm-eureka-service</module>
				<module>../hm-onboarding-service</module>
				<module>../hm-zuul-gateway-service</module>
				<module>../hm-food-service</module>
			</modules>
		</profile>
		<profile>
			<id>build-updated-only</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<modules>
				<module>../hm-common-utils</module>
				<module>../hm-auth-service</module>
				<module>../hm-eureka-service</module>
				<module>../hm-onboarding-service</module>
				<module>../hm-zuul-gateway-service</module>
				<module>../hm-food-service</module>
			</modules>
		</profile>
	</profiles>


</project>